language: node_js
node_js:
- 6.10.3
install:
- npm install
cache:
  directories:
  - node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: contact-form-api
  api_key:
    secure: chXBk3WVRbixLGoddVe9e+OFgr3WwyOuRGVQkneWd2a+01HFKOOJcn0jdJ78tk4FYsJLzZ6BPOPfDfDn8AQqH/1RnmtjnZ5dsoCoy6VLq4Fh9A5maNMjjiS9IIOwjc5KKd2Vh+YhRAhE4sD5m7xGvz0qTPVlIsOfAHeH/jrvmwOHxkeFpvh9aqeJendYE8/pg+RWaU4MxcbaeB9MV9819V7M4KadWx/VeOx28SZUioFjJApn0i61AdtggHjFtcKv1cGt912Z+L5AU560LHV8nzwZ35Um8p1rsbFe7tb5/v8Tc/VOSWGpaquWXhetIbhpHb456/sVvbfSYIlT5FA0xa/l6bQeRpMZcHlqSPZVMNz63Jo9LOnX9uPHCNBCshtYEIhMv1yEJVVtBKiWJxpRh0Qusl+nqCJTHhnbb+vndOVYuV/E4uiwDTcyNyvooBvrGPD1MRFRaIV36i57HLJQO3FW/Uqiq3uLGM1Xl+qiRHmdAXubL85Qr4eF0FXM2neH7AMimWhRDdAzf+LEfqKlTgTFvL8Np7q0/hRiKDFzaVCa6KC9DmcndrMKLXnPJRfqp0dWJfaWfXPFEXlxZseTOwcpf3LcaCX6jE9SGPhfXK/za2RURh2HjQSdhZ+E+FUQlLZVTc3COjlRdL0B2pQO0d6qyIgqPoLQKfcixTTRdv4=
  on:
    repo: codehangar/contact-form-api
    branch: master
notifications:
  slack:
    secure: h+5cGez7eeJ/xPeURDvBuj+hsk57X95gIL7KpuY1uGJQV7nySt3Mbi+b9MulCjUMpO3bi0fov76JwQWw3/yIhBmeCJn4gpKsU5KbHYXnyROb2+ZbN8CdsK35lS+OOpgnDbGcA+8CrEoFY7JBsA/BC1hl84HPipYO6UNlOuRPREBkZWkFmPcDguBXjrvlvw2thabDH6eDVeMpnvfseFRQjKXLhO/UyAbEy412drvHjvSQP+1ALegCd1qKldavjcON0cw1G4NtPNbyCXryaIk5eheNers03HZe7Tj/YRpUbMCtrbjBVNE9kcaj072gu1QlZhAf5aHUFEJe+w7wQrS5oPG+nfHUhtpG839VVrE4yLj1fVz9g3MKsFSGSyp0xG8tDGP1uy7YWY+b7TwD4Of5b4nNYJVDgbqLqoIBF8/I0a/fsbQtJ6805Yd9nrtsrt++MpwzTcj61rkteOQXjpUCvz3VYQdBvXEOGlL3mOLlm+KYylrx7qgK0vHInp30DY5avQcXizQI4X8rjHNtfhsGbJ5hqnd6pp2bNCwwsk2NS14djfrzfLngxRRmTJ+15a9R2WskUUWgzB5C4GTCl3uZnTrErhynvQLULvdbUO/o7NLv0KbGzYIOlnF0dqRRxX/EgjytE8awcxkgZe583mPmDEyjbz7u7szOv23qTTotw5w=
